#  security-config.yaml
jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC! with Auth Matrix plugin *** poi" # Custom system message
  
  securityRealm:
    local:
      users:
      - id: "admin"
        password: "admin123"

# credentials-config.yaml
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "github-credentials"
          username: "github-username"
          password: "github-token"

authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Admin role with all permissions"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "developer"
            description: "Developer role with limited permissions"
            permissions:
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
            assignments:
              - "dev-user"
