#  security-config.yaml
jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC! with Auth Matrix plugin *** poi" # Custom system message
  
  securityRealm:
    local:
      users:
      - id: "admin"
        password: "admin123"

# credentials-config.yaml
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "github-credentials"
          username: "github-username"
          password: "github-token"

authorizationStrategy:
    roleBased:
      roleDefinitions:
        global:
          - name: "admin"
            permissions:
              - "hudson.model.Hudson.Administer"
              - "hudson.model.Item.Read"
      roleAssignments:
        global:
          admin: "admin"

  markupFormatter:
    safeHtml:
      disableSyntaxHighlighting: false

jobs:
- script: >
    folder('generated') {
      properties {
        authorizationMatrix {
          inheritanceStrategy {
              nonInheriting()
          }
          entries {
            group {
              name('authenticated')
              permissions([ 'Job/Build', 'Job/Configure', 'Job/Delete', 'Job/Read' ])
            }
          }
        }
      }
    }
