#  security-config.yaml
jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC! with Auth Matrix plugin *** poi" # Custom system message
  
  securityRealm:
    local:
      users:
      - id: "admin"
        password: "admin123"

# credentials-config.yaml
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "github-credentials"
          username: "github-username"
          password: "github-token"

authorizationStrategy:
      roleBased:
        roles:
          global:
            - name: "admin"
              description: "Jenkins Administrators"
              permissions:
                - "Overall/Administer"
              entries:
                - user: "admin"
            - name: "dev"
              description: "Jenkins DEV Role"
              permissions:
                - "Overall/Read"
                - "Job/Build"
                - "Job/Read"
                - "Job/Cancel"
                - "Job/Discover"
                - "View/Read"
              entries:
                - user: "tanmayrao2"
            - name: "devops"
              description: "Jenkins DEVOPS Role"
              permissions:
                - "Overall/Read"
                - "Job/Build"
                - "Job/Read"
                - "Job/Cancel"
                - "Job/Discover"
                - "View/Read"
                - "Job/Configure"
              entries:
                - user: "tanmayrao3"

jobs:
- script: >
    folder('generated') {
      properties {
        authorizationMatrix {
          inheritanceStrategy {
              nonInheriting()
          }
          entries {
            group {
              name('authenticated')
              permissions([ 'Job/Build', 'Job/Configure', 'Job/Delete', 'Job/Read' ])
            }
          }
        }
      }
    }
