jenkins:
  systemMessage: "*** Welcome to poi-Jenkins configured with JCasC! ***"

  securityRealm:
    local:
      users:
      - id: "admin"
        password: "admin123"

# credentials-config.yaml
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "github-credentials"
          username: "github-username"
          password: "github-token"

authorizationStrategy:
  roleBased:
    roles:
      global:
      - name: "admin"
        description: "Jenkins administrators"
        permissions:
        - "Overall/Administer"
        assignments:
        - "admin"
      - name: "developer"
        description: "Jenkins developers"
        permissions:
        - "Overall/Read"
        - "Job/Build"
        - "Job/Cancel"
        assignments:
        - "developer"
