credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope: GLOBAL
          id: "github-creds"
          username: "${GITHUB_USER}"
          password: "${GITHUB_TOKEN}"
          description: "GitHub credentials"

      - kubernetes:
          scope: GLOBAL
          id: "kubernetes-creds"
          description: "Kubernetes service account credentials"
          serviceAccountName: "jenkins"

      - string:
          scope: GLOBAL
          id: "slack-token"
          secret: "${SLACK_TOKEN}"
          description: "Slack notification token"
