jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC!" # Custom system message

  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        password: "admin123"
        name: "Administrator"
        properties:
        - email: "admin@example.com"
