jenkins:
  systemMessage: "Welcome to Jenkins configured with JCasC!" # Custom system message

  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        password: "admin" # Set a strong admin password
        name: "Administrator"
        email: "admin@example.com"
