apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pkalbande/jenkins_config.git
    targetRevision: HEAD
    path: jenkins
    helm:
      valueFiles:
      - values.yaml
      - persistence-values.yaml
      #- plugins.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
