apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: jenkins
  name: jenkins-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-secret-reader
  apiGroup: rbac.authorization.k8s.io
