apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-poi
  #namespace: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    #path: "/mnt/data/jenkins" # This is the path on the Minikube host
    path: "/var/jenkins_home/casc_configs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-poi
  #namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
