controller:
  # Custom Image Configuration
  image: "parag47/test_jenkins"
  tag: "4.0"
  imagePullPolicy: Always
  imagePullSecrets:
  - name: registry-credentials
  # Basic Jenkins Controller Settings
  numExecutors: 0

  # Use existingSecret for secure password management
  controller:
  admin:
    existingSecret: jenkins-admin-secret

  httpsKeyStore:
    enable: false

  # Probes Configuration
  healthProbes: true
  probes:
    startupProbe:
      httpGet:
        path: '/login'
        port: http
      initialDelaySeconds: 120
      periodSeconds: 10
      failureThreshold: 12

  # JCasC Configuration
  JCasC:
    enabled: true
    defaultConfig: false
    configUrls:
    - https://raw.githubusercontent.com/your-org/jenkins-config/main/base-config.yaml
    - https://raw.githubusercontent.com/your-org/jenkins-config/main/credentials.yaml
    # Include seed jobs configuration
    configScripts:
      seed-jobs: |
        jobs:
          - script: >
              folder('applications') {
                  description('Application Projects')
              }
              
              multibranchPipelineJob('applications/service-one') {
                  branchSources {
                      git {
                          id('service-one')
                          remote('https://github.com/your-org/service-one.git')
                          credentialsId('github-creds')
                          traits {
                              pruneStaleBranchTrait()
                              gitBranchDiscovery()
                          }
                      }
                  }
                  triggers {
                      periodicFolderTrigger {
                          interval('5m')
                      }
                  }
              }

  # Resource Configuration
  resources:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

  # Java Options
  javaOpts: >-
    -Xms1g  -Xmx1g  -Dhudson.slaves.NodeProvisioner.initialDelay=0  -Djenkins.install.runSetupWizard=false

## RBAC Configuration
serviceAccount:
  create: true

#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::your-account:role/jenkins-role
#
serviceAccountAgent:
  create: false

#  name: "jenkins-agent"
#  annotations: {}
#
#rbac:
#  create: true
#  readSecrets: true
#
#agent:
#  enabled: true
#  defaultsProviderTemplate: "jenkins-agent"
#  jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
#  connectTimeout: 100
#  workspaceVolume:
#    type: "EmptyDir"
